In [13]:
import numpy as np
import itertools
import cv2
import random
import copy
from time import sleep, time
import pickle
import concurrent.futures
import os
import pandas as pd

In [25]:
import USDMM as USDMM
import importlib

importlib.reload(USDMM)

<module 'USDMM' from '/Users/mariana.feldman/Documents/GitHub/USDMM/USDMM.py'>

In [26]:
import USDMM as USDMM

WOMC = USDMM.WOMC(
    new = True, # True/ STR -> If True inicialize with the cross operator/ If STR it will opens the file with the name passed
    nlayer = 2, # INT -> Number of operators in each layer
    wlen = 3,  # INT -> Size of the operator (wlen*wlen)
    train_size = 10, # INT -> Number of images to train 
    val_size = 10, # INT -> Number of images to validate
    test_size = 10, # INT -> Number of images to test
    error_type = 'iou', # 'mae' / 'iou' -> type of error
    neighbors_sample = 8, # INT/False -> Number of neighbors to sort
    epoch_f = 100, # INT -> Number of epochs for the boolean function lattice (fixed windows)
    epoch_w = 50, # INT -> Number of epochs for the windows lattice
    batch = 1, # INT -> Batch size
    path_results = 'results_V2', # STR -> file where we want to save the results
    name_save='_V2', # STR -> pos fixed name for the results saved
    seed = 0, #INT -> seed for reproducibilit
    parallel = False, # True/False -> use parallel (True) or sequential (False)
    early_stop_round_f = 1e6, #20, #INT -> max number of epochs without changes in the boolean function lattice
    early_stop_round_w = 1e6 #10 #INT -> max number of epochs without changes in the windows lattice
)


#WOMC.results_after_fit()

Janela Inicializada: [array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan]), array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan])]
Joint Inicializada: [array([['00000', '1'],
       ['00001', '0'],
       ['00010', '0'],
       ['00011', '1'],
       ['00100', '0'],
       ['00101', '1'],
       ['00110', '1'],
       ['00111', '1'],
       ['01000', '1'],
       ['01001', '1'],
       ['01010', '1'],
       ['01011', '0'],
       ['01100', '1'],
       ['01101', '0'],
       ['01110', '0'],
       ['01111', '1'],
       ['10000', '0'],
       ['10001', '0'],
       ['10010', '1'],
       ['10011', '0'],
       ['10100', '1'],
       ['10101', '0'],
       ['10110', '1'],
       ['10111', '1'],
       ['11000', '0'],
       ['11001', '0'],
       ['11010', '0'],
       ['11011', '1'],
       ['11100', '0'],
       ['11101', '0'],
       ['11110', '0'],
       ['11111', '0']], dtype='<U21'), array([['00000', '0'],
       ['00001', '1'],
       ['00010', '0'],
       ['00011', '0'],
     

In [19]:
joint, error,f_epoch_min = WOMC.get_error_window_parallel(WOMC.W,WOMC.joint,0)

In [4]:
joint, error,f_epoch_min = WOMC.get_error_window_parallel(WOMC.W,WOMC.joint,0)

In [27]:
joint2, error2,f_epoch_min2 = WOMC.get_error_window(WOMC.W,WOMC.joint,0)

In [28]:
WOMC.fit()

Time: 0.03 | Epoch 0 / 50 - start Validation error:  0.4690175399714055
Time: 0.63 | Epoch 1 / 50 - Validation error: 0.29444630435423375


In [6]:
W, joint, error_min_ep = WOMC.check_great_neighboors(WOMC.W,WOMC.joint,0)

In [7]:
error_min_ep

array([0.54796682, 0.5519151 ])

In [8]:
W, joint, error_min_ep = WOMC.check_lesser_neighboors(WOMC.W,WOMC.joint,0)

In [10]:
error_min_ep

array([0.42084617, 0.4141181 ])

In [33]:
import USDMM_v2 as USDMM2
import importlib

importlib.reload(USDMM2)

<module 'USDMM_v2' from '/Users/mariana.feldman/Documents/GitHub/USDMM/USDMM_v2.py'>

In [34]:
import USDMM_v2 as USDMM2

WOMC2 = USDMM2.WOMC(
    new = True, # True/ STR -> If True inicialize with the cross operator/ If STR it will opens the file with the name passed
    nlayer = 2, # INT -> Number of operators in each layer
    wlen = 3,  # INT -> Size of the operator (wlen*wlen)
    train_size = 10, # INT -> Number of images to train 
    val_size = 10, # INT -> Number of images to validate
    test_size = 10, # INT -> Number of images to test
    error_type = 'iou', # 'mae' / 'iou' -> type of error
    neighbors_sample = False, # INT/False -> Number of neighbors to sort
    epoch_f = 10, # INT -> Number of epochs for the boolean function lattice (fixed windows)
    epoch_w = 50, # INT -> Number of epochs for the windows lattice
    batch = 10, # INT -> Batch size
    path_results = 'results_V2', # STR -> file where we want to save the results
    name_save='_V2', # STR -> pos fixed name for the results saved
    seed = 0, #INT -> seed for reproducibilit
    parallel = True, # True/False -> use parallel (True) or sequential (False)
    early_stop_round_f = 20, #INT -> max number of epochs without changes in the boolean function lattice
    early_stop_round_w = 10 #INT -> max number of epochs without changes in the windows lattice
)


Janela Inicializada: [array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan]), array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan])]
Joint Inicializada: [array([['00000', '1'],
       ['00001', '0'],
       ['00010', '0'],
       ['00011', '1'],
       ['00100', '0'],
       ['00101', '1'],
       ['00110', '1'],
       ['00111', '1'],
       ['01000', '1'],
       ['01001', '1'],
       ['01010', '1'],
       ['01011', '0'],
       ['01100', '1'],
       ['01101', '0'],
       ['01110', '0'],
       ['01111', '1'],
       ['10000', '0'],
       ['10001', '0'],
       ['10010', '1'],
       ['10011', '0'],
       ['10100', '1'],
       ['10101', '0'],
       ['10110', '1'],
       ['10111', '1'],
       ['11000', '0'],
       ['11001', '0'],
       ['11010', '0'],
       ['11011', '1'],
       ['11100', '0'],
       ['11101', '0'],
       ['11110', '0'],
       ['11111', '0']], dtype='<U21'), array([['00000', '0'],
       ['00001', '1'],
       ['00010', '0'],
       ['00011', '0'],
     

In [19]:
WOMC2.check_great_neighboors(WOMC2.W,WOMC2.joint,0)

In [ ]:
error_min_ep

array([0.54796682, 0.5519151 ])

In [20]:
W, joint, error_min_ep = WOMC.check_lesser_neighboors(WOMC.W,WOMC.joint,0)

In [ ]:
error_min_ep

array([0.42084617, 0.4141181 ])

In [29]:
WOMC2.test_neightbors()

error_train:  0.44723934003988575
error_val:  0.4476914625743703
Time: 98.09


In [32]:
WOMC2.test_neightbors()

error_train:  0.44723934003988575
error_val:  0.4476914625743703
Time: 96.46


In [35]:
WOMC2.test_neightbors()

error_train:  0.4676324458203219
error_val:  0.46828096143571274
Time: 155.69


In [2]:
Wtrain2,w_error2, W2, joint2 = WOMC.test2()

In [3]:
joint3, error3,f_epoch_min = WOMC.get_error_window_parallel(W2,joint2,0)
error3, f_epoch_min

inicial error: 0.9819856336725579
Epoch: 1: / error: 0.8794087900722621 / ix_run: 00
Min error!!
Epoch: 2: / error: 0.8202385515516838 / ix_run: 08
Min error!!
Epoch: 3: / error: 0.7492607248438035 / ix_run: 028
Min error!!
Epoch: 4: / error: 0.7325039955478129 / ix_run: 022
Min error!!
Epoch: 5: / error: 0.7143034455366941 / ix_run: 023
Min error!!
Epoch: 6: / error: 0.658144606811632 / ix_run: 07
Min error!!
Epoch: 7: / error: 0.6432813063414392 / ix_run: 015
Min error!!
Epoch: 8: / error: 0.6252427460365892 / ix_run: 027
Min error!!
Epoch: 9: / error: 0.6190743481502106 / ix_run: 06
Min error!!
Epoch: 10: / error: 0.6174760123377236 / ix_run: 012
Min error!!


(array([0.61747601, 0.61736838]), 10)

In [5]:
import USDMM as USDMM

WOMC = USDMM.WOMC(
    new = True, # True/ STR -> If True inicialize with the cross operator/ If STR it will opens the file with the name passed
    nlayer = 2, # INT -> Number of operators in each layer
    wlen = 3,  # INT -> Size of the operator (wlen*wlen)
    train_size = 10, # INT -> Number of images to train 
    val_size = 10, # INT -> Number of images to validate
    test_size = 10, # INT -> Number of images to test
    error_type = 'iou', # 'mae' / 'iou' -> type of error
    neighbors_sample = False, # INT/False -> Number of neighbors to sort
    epoch_f = 10, # INT -> Number of epochs for the boolean function lattice (fixed windows)
    epoch_w = 50, # INT -> Number of epochs for the windows lattice
    batch = 10, # INT -> Batch size
    path_results = 'results_V4', # STR -> file where we want to save the results
    name_save='_V4', # STR -> pos fixed name for the results saved
    seed = 0, #INT -> seed for reproducibilit
    parallel = True, # True/False -> use parallel (True) or sequential (False)
    early_stop_round_f = 20, #INT -> max number of epochs without changes in the boolean function lattice
    early_stop_round_w = 10 #INT -> max number of epochs without changes in the windows lattice
)

Janela Inicializada: [array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan]), array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan])]
Joint Inicializada: [array([['00000', '1'],
       ['00001', '0'],
       ['00010', '0'],
       ['00011', '1'],
       ['00100', '0'],
       ['00101', '1'],
       ['00110', '1'],
       ['00111', '1'],
       ['01000', '1'],
       ['01001', '1'],
       ['01010', '1'],
       ['01011', '0'],
       ['01100', '1'],
       ['01101', '0'],
       ['01110', '0'],
       ['01111', '1'],
       ['10000', '0'],
       ['10001', '0'],
       ['10010', '1'],
       ['10011', '0'],
       ['10100', '1'],
       ['10101', '0'],
       ['10110', '1'],
       ['10111', '1'],
       ['11000', '0'],
       ['11001', '0'],
       ['11010', '0'],
       ['11011', '1'],
       ['11100', '0'],
       ['11101', '0'],
       ['11110', '0'],
       ['11111', '0']], dtype='<U11'), array([['00000', '0'],
       ['00001', '1'],
       ['00010', '0'],
       ['00011', '0'],
     

In [6]:
Wtrain,w_error, W, joint = WOMC.test2()

In [7]:
joint4, error4,f_epoch_min = WOMC.get_error_window_parallel(W,joint,0)
error4, f_epoch_min

inicial error: 0.9819856336725579
Epoch: 1: / error: 0.8794087900722621 / ix_run: 00


KeyboardInterrupt: 

In [8]:
import numpy as np
error_hist = np.load('./results_V4/run/error_ep_1.txt', allow_pickle=True)
error_hist2 = np.load('./results_V2/run/error_ep_1.txt', allow_pickle=True)

In [11]:
min(error_hist['error']), min(error_hist2['error'])

(0.8794087900722621, 0.9819856336725579)

In [14]:
len(error_hist['error']), len(error_hist2['error'])

(64, 64)

In [20]:
error_hist['joint'][0][0][0][1]

'1'

In [21]:
for i in range(len(error_hist['joint'])):
    #if error_hist['error'][i] !=error_hist2['error'][i]:
        #print(i)
    count = 0
    for k in range(2):
        for j in range(len(error_hist['joint'][i][k])):
            if error_hist['joint'][i][k][j][1] != error_hist['joint'][i][k][j][1]:
                count+=1
    print(f'round - {i} / count ={count}')

round - 0 / count =0
round - 1 / count =0
round - 2 / count =0
round - 3 / count =0
round - 4 / count =0
round - 5 / count =0
round - 6 / count =0
round - 7 / count =0
round - 8 / count =0
round - 9 / count =0
round - 10 / count =0
round - 11 / count =0
round - 12 / count =0
round - 13 / count =0
round - 14 / count =0
round - 15 / count =0
round - 16 / count =0
round - 17 / count =0
round - 18 / count =0
round - 19 / count =0
round - 20 / count =0
round - 21 / count =0
round - 22 / count =0
round - 23 / count =0
round - 24 / count =0
round - 25 / count =0
round - 26 / count =0
round - 27 / count =0
round - 28 / count =0
round - 29 / count =0
round - 30 / count =0
round - 31 / count =0
round - 32 / count =0
round - 33 / count =0
round - 34 / count =0
round - 35 / count =0
round - 36 / count =0
round - 37 / count =0
round - 38 / count =0
round - 39 / count =0
round - 40 / count =0
round - 41 / count =0
round - 42 / count =0
round - 43 / count =0
round - 44 / count =0
round - 45 / count =

In [7]:
joint4, error4,f_epoch_min = WOMC.get_error_window_parallel(W,joint,0)
error4, f_epoch_min

(array([0.61383145, 0.60987238]), 14)

In [9]:
import pickle
pickle.dump(joint4, open('joint4', 'wb'))

In [3]:
import pickle
pickle.dump(W2, open('W', 'wb'))

In [3]:
path_results = 'results_V4'
name_save = '_V4'

In [4]:
import numpy as np

In [5]:
joint = np.load(f'{path_results}/joint{name_save}.txt', allow_pickle=True)
W = np.load(f'{path_results}/W{name_save}.txt', allow_pickle=True)

In [6]:
W

[array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan]),
 array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan])]

In [5]:
WOMC.results_after_fit('results_V4', '_V4')

Reading from: results_V4
Train error: 0.6138314515405996 / Validation error: 0.609872383871108 / Test error: 0.6210821757434946


TypeError: 'int' object is not subscriptable

In [8]:
joint4

[array([['00000', '0'],
        ['00001', '0'],
        ['00010', '0'],
        ['00011', '1'],
        ['00100', '0'],
        ['00101', '0'],
        ['00110', '0'],
        ['00111', '0'],
        ['01000', '0'],
        ['01001', '1'],
        ['01010', '0'],
        ['01011', '1'],
        ['01100', '0'],
        ['01101', '0'],
        ['01110', '1'],
        ['01111', '0'],
        ['10000', '0'],
        ['10001', '0'],
        ['10010', '1'],
        ['10011', '0'],
        ['10100', '1'],
        ['10101', '0'],
        ['10110', '0'],
        ['10111', '0'],
        ['11000', '0'],
        ['11001', '0'],
        ['11010', '0'],
        ['11011', '0'],
        ['11100', '1'],
        ['11101', '0'],
        ['11110', '0'],
        ['11111', '0']], dtype='<U11'),
 array([['00000', '0'],
        ['00001', '1'],
        ['00010', '0'],
        ['00011', '0'],
        ['00100', '1'],
        ['00101', '0'],
        ['00110', '1'],
        ['00111', '1'],
        ['01000', '1'],


In [ ]:
error3==error4

In [11]:
w_error == w_error2

(0.9819856336725579, 0.9819856336725579)

In [42]:
w_error, w_error2

(0.9819856336725579, 0.9825991306050732)

In [12]:
count = 0
for k in range(2):
    for j in range(len(joint[k])):
        if joint[k][j][1] != joint2[k][j][1]:
            count+=1
count

0

In [13]:
W, W2

([array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan]),
  array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan])],
 [array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan]),
  array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan])])

In [14]:
len(Wtrain)

10

In [15]:
len(Wtrain[0])

2

In [16]:
Wtrain[0][1] == Wtrain2[0][1]

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [17]:
import numpy as np

In [18]:
for k in range(len(Wtrain)):
    print(np.all(Wtrain[k][-1] == Wtrain2[k][-1]))

True
True
True
True
True
True
True
True
True
True


In [6]:
train, ytrain = WOMC.get_images(10, 'train')

In [7]:
train

[array([[-1., -1., -1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1., -1.],
        ...,
        [-1., -1., -1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1., -1.]]),
 array([[-1., -1., -1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1., -1.],
        ...,
        [-1., -1., -1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1., -1.]]),
 array([[-1., -1., -1., ..., -1., -1., -1.],
        [-1., -1.,  1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1., -1.],
        ...,
        [-1., -1., -1., ..., -1., -1., -1.],
        [-1.,  1., -1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1., -1.]]),
 array([[-1., -1., -1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1.,  1.],
        [-1., -1., -1., ..., -1., -1., -1.],
        ..

In [9]:
train[0].shape

(56, 56)

In [11]:
import numpy as np

In [7]:
img = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12],[13,14,15,16]])

In [20]:
img = np.array([[1,-1,-1,-1], [1,1,-1,-1], [1,1,1,1],[-1,-1,1,1]], dtype=np.float32)
img

array([[ 1., -1., -1., -1.],
       [ 1.,  1., -1., -1.],
       [ 1.,  1.,  1.,  1.],
       [-1., -1.,  1.,  1.]], dtype=float32)

In [34]:
def find_minterms(truth_table):
    inputs = truth_table[:, 0]
    results = truth_table[:, 1]
    minterms = []
    for i in np.where(results =='1')[0]:
        minterms.append(inputs[i])
    minterms

    return minterms

def create_w_matrices(W, joint):
    matrices = []
    for k in range(2):
        matrix_k = []
        reduced_minterms = find_minterms(joint[k])
        for minterm in range(len(reduced_minterms)):
            matrix = np.copy(W[k])
            c=0
            for i in np.where(W[k]==1)[0]:
                matrix[i] = reduced_minterms[minterm][c]
                c+=1
            matrix = np.where(matrix==0,-1,matrix)
            matrix = np.nan_to_num(matrix)
            matrix_k.append(matrix.reshape((3, 3)))
        matrices.append(matrix_k)
    return matrices

In [33]:
joint[1]

array([['00000', '0'],
       ['00001', '1'],
       ['00010', '0'],
       ['00011', '0'],
       ['00100', '1'],
       ['00101', '0'],
       ['00110', '1'],
       ['00111', '1'],
       ['01000', '1'],
       ['01001', '0'],
       ['01010', '0'],
       ['01011', '1'],
       ['01100', '0'],
       ['01101', '0'],
       ['01110', '0'],
       ['01111', '0'],
       ['10000', '1'],
       ['10001', '0'],
       ['10010', '0'],
       ['10011', '0'],
       ['10100', '0'],
       ['10101', '1'],
       ['10110', '0'],
       ['10111', '0'],
       ['11000', '1'],
       ['11001', '1'],
       ['11010', '1'],
       ['11011', '0'],
       ['11100', '0'],
       ['11101', '1'],
       ['11110', '1'],
       ['11111', '1']], dtype='<U11')

In [35]:
W_matrices = create_w_matrices(W, joint)

In [36]:
for kernel in W_matrices[0]:
    print(kernel)

[[ 0. -1.  0.]
 [-1. -1.  1.]
 [ 0.  1.  0.]]
[[ 0. -1.  0.]
 [ 1. -1. -1.]
 [ 0.  1.  0.]]
[[ 0. -1.  0.]
 [ 1. -1.  1.]
 [ 0.  1.  0.]]
[[ 0. -1.  0.]
 [ 1.  1.  1.]
 [ 0. -1.  0.]]
[[ 0.  1.  0.]
 [-1. -1.  1.]
 [ 0. -1.  0.]]
[[ 0.  1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  0.]]
[[ 0.  1.  0.]
 [ 1.  1. -1.]
 [ 0. -1.  0.]]


In [37]:
img_c = np.zeros([img.shape[0], img.shape[1]], dtype=float)
for kernel in W_matrices[0]:
    img_b = cv2.copyMakeBorder(img, 1, 1, 1, 1, cv2.BORDER_CONSTANT, None, value = -1) 
    img_r = cv2.filter2D(img_b, -1, kernel)
    img_r = img_r-4
    img_r = (img_r > 0).astype(float)
    img_c += img_r[1:img_r.shape[0]-1, 1:img_r.shape[1]-1]
img_c[img_c == 0] = -1
img_c

array([[-1.,  1., -1., -1.],
       [-1., -1.,  1., -1.],
       [-1., -1., -1., -1.],
       [-1.,  1., -1.,  1.]])

In [40]:
W_matrices[1]

[array([[ 0., -1.,  0.],
        [-1., -1., -1.],
        [ 0.,  1.,  0.]]),
 array([[ 0., -1.,  0.],
        [-1.,  1., -1.],
        [ 0., -1.,  0.]]),
 array([[ 0., -1.,  0.],
        [-1.,  1.,  1.],
        [ 0., -1.,  0.]]),
 array([[ 0., -1.,  0.],
        [-1.,  1.,  1.],
        [ 0.,  1.,  0.]]),
 array([[ 0., -1.,  0.],
        [ 1., -1., -1.],
        [ 0., -1.,  0.]]),
 array([[ 0., -1.,  0.],
        [ 1., -1.,  1.],
        [ 0.,  1.,  0.]]),
 array([[ 0.,  1.,  0.],
        [-1., -1., -1.],
        [ 0., -1.,  0.]]),
 array([[ 0.,  1.,  0.],
        [-1.,  1., -1.],
        [ 0.,  1.,  0.]]),
 array([[ 0.,  1.,  0.],
        [ 1., -1., -1.],
        [ 0., -1.,  0.]]),
 array([[ 0.,  1.,  0.],
        [ 1., -1., -1.],
        [ 0.,  1.,  0.]]),
 array([[ 0.,  1.,  0.],
        [ 1., -1.,  1.],
        [ 0., -1.,  0.]]),
 array([[ 0.,  1.,  0.],
        [ 1.,  1., -1.],
        [ 0.,  1.,  0.]]),
 array([[ 0.,  1.,  0.],
        [ 1.,  1.,  1.],
        [ 0., -1.,  0.]]),

In [24]:
np.random.randn(3, 3, 3)

array([[[-0.06577144,  0.18124466,  0.13609102],
        [-0.07447521, -0.86875002, -0.79689841],
        [-0.79329713, -0.30520855,  0.31954863]],

       [[-0.36840675, -0.02148489, -0.18242121],
        [ 1.29503907,  0.10903903, -0.21521149],
        [-0.58317074, -0.53785977, -0.01604245]],

       [[ 0.26258116,  0.64577224,  0.55541722],
        [ 0.69212453, -0.46089375, -0.30454234],
        [ 1.81784468,  0.374458  , -2.02508485]]])

In [41]:
np.random.randint(0, 2, size=(56, 56, 3))

array([[[0, 0, 1],
        [0, 0, 1],
        [0, 0, 0],
        ...,
        [1, 1, 0],
        [0, 0, 0],
        [0, 0, 1]],

       [[1, 0, 1],
        [1, 1, 0],
        [1, 0, 1],
        ...,
        [1, 1, 0],
        [1, 0, 1],
        [1, 1, 0]],

       [[0, 0, 0],
        [0, 1, 0],
        [1, 1, 1],
        ...,
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 0]],

       ...,

       [[0, 1, 1],
        [0, 0, 1],
        [0, 1, 0],
        ...,
        [1, 1, 0],
        [1, 1, 1],
        [1, 1, 0]],

       [[0, 1, 0],
        [0, 1, 1],
        [1, 1, 1],
        ...,
        [1, 1, 1],
        [1, 0, 1],
        [0, 0, 1]],

       [[1, 0, 0],
        [1, 1, 0],
        [0, 1, 1],
        ...,
        [1, 0, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [57]:
Wt = np.array([ np.nan,  np.nan,  np.nan,   np.nan,  1.,  1.,  np.nan,  1.,  np.nan])

In [62]:
def create_joint(W):
    Ji=[]
    ni = int(W[~np.isnan(W)].sum())
    for i in itertools.product([0, 1], repeat=ni):
        Ji.append(''.join(np.array(i).astype(str)))
    return Ji

In [59]:
def find_minterms(truth_table):
    inputs = truth_table[:, 0]
    results = truth_table[:, 1]
    minterms = []
    for i in np.where(results =='1')[0]:
        minterms.append(inputs[i])
    minterms

    return minterms

In [64]:
def create_w_matrices(W):
    matrices = []
    for k in range(1):
        matrix_k = []
        reduced_minterms = create_joint(W[k])
        for minterm in range(len(reduced_minterms)):
            matrix = np.copy(W[k])
            c=0
            for i in np.where(W[k]==1)[0]:
                matrix[i] = reduced_minterms[minterm][c]
                c+=1
            matrix = np.where(matrix==0,-1,matrix)
            matrix = np.nan_to_num(matrix)
            matrix_k.append(matrix.reshape((3, 3)))
        matrices.append(matrix_k)
    return matrices

In [66]:
W_m = create_w_matrices([Wt])[0]
W_m

[array([[ 0.,  0.,  0.],
        [ 0., -1., -1.],
        [ 0., -1.,  0.]]),
 array([[ 0.,  0.,  0.],
        [ 0., -1., -1.],
        [ 0.,  1.,  0.]]),
 array([[ 0.,  0.,  0.],
        [ 0., -1.,  1.],
        [ 0., -1.,  0.]]),
 array([[ 0.,  0.,  0.],
        [ 0., -1.,  1.],
        [ 0.,  1.,  0.]]),
 array([[ 0.,  0.,  0.],
        [ 0.,  1., -1.],
        [ 0., -1.,  0.]]),
 array([[ 0.,  0.,  0.],
        [ 0.,  1., -1.],
        [ 0.,  1.,  0.]]),
 array([[ 0.,  0.,  0.],
        [ 0.,  1.,  1.],
        [ 0., -1.,  0.]]),
 array([[0., 0., 0.],
        [0., 1., 1.],
        [0., 1., 0.]])]

In [83]:
def create_joint_t():
    # Suponha que a função retorna valores fictícios para W e weights
    W = 1
    weights = [0.1, 0.2, 0.3]
    return W, weights

# Número de vezes que você deseja chamar a função
n = 5

# Use list comprehensions para gerar as listas
list_W, list_weights = zip(*[create_joint_t() for _ in range(n)])

# Exemplo de saída
print("Lista de W:", list_W)
print("Lista de weights:", list_weights)

Lista de W: (1, 1, 1, 1, 1)
Lista de weights: ([0.1, 0.2, 0.3], [0.1, 0.2, 0.3], [0.1, 0.2, 0.3], [0.1, 0.2, 0.3], [0.1, 0.2, 0.3])


In [85]:
list_W[0]

1

In [82]:
np.random.randint(2, size=len(W_m))

array([1, 1, 0, 0, 1, 0, 0, 0])

In [71]:
_w = np.array([1, 0, 0, 0, 0, 0, 0, 1])
_w

array([1, 0, 0, 0, 0, 0, 0, 1])

In [81]:
for ii in np.array(W_m) * _w[:, np.newaxis, np.newaxis]:
    print(ii)
    print('-----')

[[ 0.  0.  0.]
 [ 0. -1. -1.]
 [ 0. -1.  0.]]
-----
[[ 0.  0.  0.]
 [ 0. -0. -0.]
 [ 0.  0.  0.]]
-----
[[ 0.  0.  0.]
 [ 0. -0.  0.]
 [ 0. -0.  0.]]
-----
[[ 0.  0.  0.]
 [ 0. -0.  0.]
 [ 0.  0.  0.]]
-----
[[ 0.  0.  0.]
 [ 0.  0. -0.]
 [ 0. -0.  0.]]
-----
[[ 0.  0.  0.]
 [ 0.  0. -0.]
 [ 0.  0.  0.]]
-----
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0. -0.  0.]]
-----
[[0. 0. 0.]
 [0. 1. 1.]
 [0. 1. 0.]]
-----


In [72]:
[array * weight for array, weight in zip(W_m, _w) if weight == 1]

[array([[ 0.,  0.,  0.],
        [ 0., -1., -1.],
        [ 0., -1.,  0.]]),
 array([[0., 0., 0.],
        [0., 1., 1.],
        [0., 1., 0.]])]

In [76]:
_w[:, np.newaxis, np.newaxis].shape

(8, 1, 1)

In [77]:
img = np.array([[-1,2,-3,4], [-5,6,7,-8], [9,-10,-11,12],[13,14,15,16]])
(img > 0).astype(float)

array([[0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [78]:
#crie uma matriz 3x3 de zeros

img = np.zeros((3,3)) - 4
img

array([[-4., -4., -4.],
       [-4., -4., -4.],
       [-4., -4., -4.]])

In [79]:
(img > 0).astype(float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [73]:
np.array(W_m) * _w[:, np.newaxis, np.newaxis]

array([[[ 0.,  0.,  0.],
        [ 0., -1., -1.],
        [ 0., -1.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0., -0., -0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0., -0.,  0.],
        [ 0., -0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0., -0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0., -0.],
        [ 0., -0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0., -0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0., -0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  1.,  1.],
        [ 0.,  1.,  0.]]])

In [70]:
_w* W_m

ValueError: operands could not be broadcast together with shapes (8,) (8,3,3) 

In [67]:
len(W_m)

8

In [63]:
jt = create_joint(Wt)
jt

['000', '001', '010', '011', '100', '101', '110', '111']

In [61]:
find_minterms(jt)

['000', '001', '010', '011', '100', '101', '110', '111']

In [99]:
nlayer=2
for k in reversed(range(nlayer)):
    print(k)

1
0


In [94]:
a = list(range(5))

In [95]:
a.reverse()

In [1]:
Wtrain

NameError: name 'Wtrain' is not defined

In [100]:
import numpy as np
import cv2

def convolution(image, kernel):
    return cv2.filter2D(image, -1, kernel)

def tanh(x):
    return np.tanh(x)

def initialize_parameters_2_layers(num_channels):
    np.random.seed(42)
    filters_layer1 = np.random.randn(3, 3, num_channels)  # Example: 3x3 filter for the first layer with 3 channels
    filters_layer2 = np.random.randn(3, 3)  # Example: 3x3 filter for the second layer (assuming 1 channel output)
    return filters_layer1, filters_layer2

def forward_propagation(image, filters_layer1, filters_layer2):
    # First convolution layer
    conv_result1 = np.zeros((image.shape[0] - filters_layer1.shape[0] + 1,
                             image.shape[1] - filters_layer1.shape[1] + 1,
                             filters_layer1.shape[2]))

    for channel in range(filters_layer1.shape[2]):
        conv_result1[:, :, channel] = convolution(image[:, :, channel], filters_layer1[:, :, channel])

    activated_result1 = tanh(conv_result1)

    # Second convolution layer
    conv_result2 = convolution(activated_result1.sum(axis=2), filters_layer2)
    activated_result2 = tanh(conv_result2)

    return conv_result1, activated_result1, conv_result2, activated_result2

def backward_propagation(image, conv_result1, activated_result1, conv_result2, activated_result2,
                         filters_layer1, filters_layer2, learning_rate=0.01):
    # Backward pass for the second layer
    error2 = image[:, :, 0] - activated_result2
    gradient2 = -2 * error2 * (1 - activated_result2**2)  # Derivative of tanh
    filters_layer2 -= learning_rate * convolution(activated_result1.sum(axis=2), gradient2)

    # Backward pass for the first layer
    error1 = np.zeros_like(conv_result1)
    for channel in range(filters_layer1.shape[2]):
        error1[:, :, channel] = convolution(gradient2, filters_layer2[:, :, 0])
    
    gradient1 = -2 * error1 * (1 - activated_result1**2)  # Derivative of tanh
    for channel in range(filters_layer1.shape[2]):
        filters_layer1[:, :, channel] -= learning_rate * convolution(image[:, :, channel], gradient1[:, :, channel])

def train_cnn_2_layers(images, epochs=100, learning_rate=0.01):
    # Initialize parameters
    num_channels = images[0].shape[2]
    filters_layer1, filters_layer2 = initialize_parameters_2_layers(num_channels)

    # Training loop
    for epoch in range(epochs):
        for image in images:
            # Forward pass
            conv_result1, activated_result1, conv_result2, activated_result2 = forward_propagation(
                image, filters_layer1, filters_layer2)

            # Backward pass (gradient descent)
            backward_propagation(image, conv_result1, activated_result1, conv_result2, activated_result2,
                                 filters_layer1, filters_layer2, learning_rate)

    return filters_layer1, filters_layer2

# Exemplo de uso
# Suponha que 'color_images' seja uma lista de imagens coloridas (3 canais)
color_images = [np.random.randint(0, 2, size=(56, 56, 3)) for _ in range(100000)]
trained_filters_layer1, trained_filters_layer2 = train_cnn_2_layers(color_images)


error: OpenCV(4.7.0) /Users/runner/work/opencv-python/opencv-python/opencv/modules/imgproc/src/filter.simd.hpp:3297: error: (-213:The function/feature is not implemented) Unsupported combination of source format (=4), and destination format (=4) in function 'getLinearFilter'


In [102]:
color_images[0]

array([[[1, 1, 0],
        [0, 1, 0],
        [1, 0, 1],
        ...,
        [1, 1, 0],
        [1, 1, 0],
        [0, 1, 1]],

       [[1, 1, 1],
        [0, 1, 1],
        [1, 1, 1],
        ...,
        [1, 0, 0],
        [0, 0, 1],
        [0, 1, 1]],

       [[0, 0, 0],
        [0, 0, 1],
        [1, 0, 0],
        ...,
        [1, 1, 0],
        [1, 0, 1],
        [0, 1, 0]],

       ...,

       [[0, 0, 1],
        [0, 0, 0],
        [0, 1, 0],
        ...,
        [1, 1, 1],
        [1, 1, 1],
        [0, 0, 1]],

       [[0, 0, 1],
        [0, 0, 0],
        [0, 0, 1],
        ...,
        [0, 0, 1],
        [1, 0, 1],
        [1, 0, 1]],

       [[0, 0, 1],
        [0, 0, 0],
        [1, 0, 0],
        ...,
        [0, 1, 1],
        [1, 0, 1],
        [0, 0, 1]]])

In [ ]:
import numpy as np
import cv2

def convolution(image, kernel):
    return cv2.filter2D(image, -1, kernel)

def relu(x):
    return np.maximum(0, x)

def initialize_parameters_2_layers(num_channels):
    np.random.seed(42)
    filters_layer1 = np.random.randn(3, 3, num_channels)  # Example: 3x3 filter for the first layer with 3 channels
    filters_layer2 = np.random.randn(3, 3)  # Example: 3x3 filter for the second layer (assuming 1 channel output)
    return filters_layer1, filters_layer2

def forward_propagation(image, filters_layer1, filters_layer2):
    # First convolution layer
    conv_result1 = np.zeros((image.shape[0] - filters_layer1.shape[0] + 1,
                             image.shape[1] - filters_layer1.shape[1] + 1,
                             filters_layer1.shape[2]))

    for channel in range(filters_layer1.shape[2]):
        conv_result1[:, :, channel] = convolution(image[:, :, channel], filters_layer1[:, :, channel])

    activated_result1 = relu(conv_result1)

    # Second convolution layer
    conv_result2 = convolution(activated_result1.sum(axis=2), filters_layer2)
    activated_result2 = relu(conv_result2)

    return conv_result1, activated_result1, conv_result2, activated_result2

def backward_propagation(image, conv_result1, activated_result1, conv_result2, activated_result2,
                         filters_layer1, filters_layer2, learning_rate=0.01):
    # Backward pass for the second layer
    error2 = image[:, :, 0] - activated_result2
    gradient2 = -2 * error2 * (conv_result2 > 0)
    filters_layer2 -= learning_rate * convolution(activated_result1.sum(axis=2), gradient2)

    # Backward pass for the first layer
    error1 = np.zeros_like(conv_result1)
    for channel in range(filters_layer1.shape[2]):
        error1[:, :, channel] = convolution(gradient2, filters_layer2[:, :, 0])
    
    gradient1 = -2 * error1 * (conv_result1 > 0)
    for channel in range(filters_layer1.shape[2]):
        filters_layer1[:, :, channel] -= learning_rate * convolution(image[:, :, channel], gradient1[:, :, channel])

def train_cnn_2_layers(images, epochs=100, learning_rate=0.01):
    # Initialize parameters
    num_channels = images[0].shape[2]
    filters_layer1, filters_layer2 = initialize_parameters_2_layers(num_channels)

    # Training loop
    for epoch in range(epochs):
        for image in images:
            # Forward pass
            conv_result1, activated_result1, conv_result2, activated_result2 = forward_propagation(
                image, filters_layer1, filters_layer2)

            # Backward pass (gradient descent)
            backward_propagation(image, conv_result1, activated_result1, conv_result2, activated_result2,
                                 filters_layer1, filters_layer2, learning_rate)

    return filters_layer1, filters_layer2

# Exemplo de uso
# Suponha que 'color_images' seja uma lista de imagens coloridas (3 canais)
color_images = [np.random.randint(0, 2, size=(56, 56, 3)) for _ in range(100000)]
trained_filters_layer1, trained_filters_layer2 = train_cnn_2_layers(color_images)

In [ ]:
import numpy as np
import cv2

def convolution(image, kernel):
    return cv2.filter2D(image, -1, kernel)

def relu(x):
    return np.maximum(0, x)

def initialize_parameters_2_layers():
    np.random.seed(42)
    filters_layer1 = np.random.randn(3, 3)  # Example: 3x3 filter for the first layer
    filters_layer2 = np.random.randn(3, 3)  # Example: 3x3 filter for the second layer
    return filters_layer1, filters_layer2

def forward_propagation(image, filters_layer1, filters_layer2):
    # First convolution layer
    conv_result1 = convolution(image, filters_layer1)
    activated_result1 = relu(conv_result1)

    # Second convolution layer
    conv_result2 = convolution(activated_result1, filters_layer2)
    activated_result2 = relu(conv_result2)

    return conv_result1, activated_result1, conv_result2, activated_result2

def backward_propagation(image, conv_result1, activated_result1, conv_result2, activated_result2,
                         filters_layer1, filters_layer2, learning_rate=0.01):
    # Backward pass for the second layer
    error2 = image - activated_result2
    gradient2 = -2 * error2 * (conv_result2 > 0)
    filters_layer2 -= learning_rate * convolution(activated_result1, gradient2)

    # Backward pass for the first layer
    error1 = convolution(gradient2, filters_layer2.T)
    gradient1 = -2 * error1 * (conv_result1 > 0)
    filters_layer1 -= learning_rate * convolution(image, gradient1)

def train_cnn_2_layers(images, epochs=100, learning_rate=0.01):
    # Initialize parameters
    filters_layer1, filters_layer2 = initialize_parameters_2_layers()

    # Training loop
    for epoch in range(epochs):
        for image in images:
            # Forward pass
            conv_result1, activated_result1, conv_result2, activated_result2 = forward_propagation(
                image, filters_layer1, filters_layer2)

            # Backward pass (gradient descent)
            backward_propagation(image, conv_result1, activated_result1, conv_result2, activated_result2,
                                 filters_layer1, filters_layer2, learning_rate)

    return filters_layer1, filters_layer2

# Exemplo de uso
# Suponha que 'binary_images' seja uma lista de imagens binárias (matrizes 2D de 0s e 1s)
trained_filters_layer1, trained_filters_layer2 = train_cnn_2_layers(binary_images)


In [18]:
tt = np.array([[1,2,3,5,6,7,9,10,11],[2,3,4,6,7,8,10,11,12],[5,6,7,9,10,11,13,14,15],[6,7,8,10,11,12,14,15,16]])

In [19]:
tt

array([[ 1,  2,  3,  5,  6,  7,  9, 10, 11],
       [ 2,  3,  4,  6,  7,  8, 10, 11, 12],
       [ 5,  6,  7,  9, 10, 11, 13, 14, 15],
       [ 6,  7,  8, 10, 11, 12, 14, 15, 16]])

In [20]:
Wini = np.array([np.nan, 1., np.nan, 1., 1., 1., np.nan, 1., np.nan])

In [41]:
arr = tt*Wini
arr

array([[nan,  2., nan,  5.,  6.,  7., nan, 10., nan],
       [nan,  3., nan,  6.,  7.,  8., nan, 11., nan],
       [nan,  6., nan,  9., 10., 11., nan, 14., nan],
       [nan,  7., nan, 10., 11., 12., nan, 15., nan]])

In [42]:
cleaned_array = [row[~np.isnan(row)] for row in arr]
result_array = np.array(cleaned_array)
result_array

array([[ 2.,  5.,  6.,  7., 10.],
       [ 3.,  6.,  7.,  8., 11.],
       [ 6.,  9., 10., 11., 14.],
       [ 7., 10., 11., 12., 15.]])

In [23]:
wlen = 3
increase = int(round(wlen/2-0.1,0))

In [69]:
def get_images(img_size, img_type):
    ximg = []
    yimg = []
    for img in range(1,img_size+1):
        x = cv2.imread(f'./data/x/{img_type}{img:02d}.jpg', cv2.IMREAD_GRAYSCALE)
        y = cv2.imread(f'./data/y/{img_type}{img:02d}.jpg', cv2.IMREAD_GRAYSCALE)
        xbin = _convert_binary(x)
        xbin_inc = increase_zero(xbin)
        ybin = _convert_binary(y)
        for i in range(xbin.shape[0]):
            for j in range(xbin.shape[1]):
                window = np.array(xbin_inc[i:i + wlen, j:j + wlen]).flatten()
                window = (xbin_inc[i:i + wlen, j:j + wlen]).flatten()
                ximg.append(window)
                yimg.append(ybin[i, j])
    return np.vstack(ximg) , np.array(yimg)

def increase_zero(img):
    img_inc = -np.ones((img.shape[0]+increase*2, img.shape[1]+increase*2), dtype=img.dtype)
    img_inc[increase:img_inc.shape[0]-increase,increase:img_inc.shape[1]-increase] = img
    return img_inc

def _convert_binary(img):
    (_, img_bin) = cv2.threshold(img, 100, 255, cv2.THRESH_BINARY)
    img_bin = img_bin.astype('float64')
    img_bin[(img_bin==0)]=1
    img_bin[(img_bin==255)]=-1    
    return img_bin

In [70]:
train_size = 10
img_type = 'train'

In [71]:
x, y = get_images(train_size, 'train')

In [74]:
x.shape, y.shape

((31360, 9), (31360,))

In [78]:
xbin.shape[0]

56

In [87]:
W = []
W.append(np.array([np.nan, 1., np.nan, 1., 1., 1., np.nan, 1., np.nan]))
W.append(np.array([np.nan, 1., np.nan, 1., 1., 1., np.nan, 1., np.nan]))
np.nansum(W, axis=1)

array([5., 5.])

In [84]:
2**5

32

In [65]:
a = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15]])

In [68]:
a.flatten().values

AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [17]:
import numpy as np

def sliding_window(matrix, window_size):
    """
    Generate submatrices using a sliding window over a 2D matrix.

    Args:
        matrix (numpy.ndarray): The input 2D matrix.
        window_size (tuple): A tuple (height, width) representing the window size.

    Yields:
        numpy.ndarray: Submatrices corresponding to each position of the sliding window.
    """
    if not isinstance(matrix, np.ndarray):
        matrix = np.array(matrix)

    if not isinstance(window_size, tuple) or len(window_size) != 2:
        raise ValueError("window_size must be a tuple of two integers (height, width).")

    height, width = window_size
    matrix_height, matrix_width = matrix.shape

    if height > matrix_height or width > matrix_width:
        raise ValueError("Window size exceeds the matrix dimensions.")

    for i in range(matrix_height - height + 1):
        for j in range(matrix_width - width + 1):
            window = matrix[i:i + height, j:j + width].fl
            yield window

# Example usage:
matrix = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15]])

window_size = (2, 2)

for submatrix in sliding_window(matrix, window_size):
    print(submatrix)


[[1 2]
 [6 7]]
[[2 3]
 [7 8]]
[[3 4]
 [8 9]]
[[ 4  5]
 [ 9 10]]
[[ 6  7]
 [11 12]]
[[ 7  8]
 [12 13]]
[[ 8  9]
 [13 14]]
[[ 9 10]
 [14 15]]


In [37]:
np.array(submatrix).flatten()

array([ 9, 10, 14, 15])

In [35]:
a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

In [2]:
import USDMM_v3 as USDMM

WOMC = USDMM.WOMC(
    new = True, # True/ STR -> If True inicialize with the cross operator/ If STR it will opens the file with the name passed
    nlayer = 2, # INT -> Number of operators in each layer
    wlen = 3,  # INT -> Size of the operator (wlen*wlen)
    train_size = 10, # INT -> Number of images to train 
    val_size = 10, # INT -> Number of images to validate
    test_size = 10, # INT -> Number of images to test
    error_type = 'iou', # 'mae' / 'iou' -> type of error
    neighbors_sample = False, # INT/False -> Number of neighbors to sort
    epoch_f = 10, # INT -> Number of epochs for the boolean function lattice (fixed windows)
    epoch_w = 50, # INT -> Number of epochs for the windows lattice
    batch = 10, # INT -> Batch size
    path_results = 'results_V4', # STR -> file where we want to save the results
    name_save='_V4', # STR -> pos fixed name for the results saved
    seed = 0, #INT -> seed for reproducibilit
    parallel = True, # True/False -> use parallel (True) or sequential (False)
    early_stop_round_f = 20, #INT -> max number of epochs without changes in the boolean function lattice
    early_stop_round_w = 10 #INT -> max number of epochs without changes in the windows lattice
)

Janela Inicializada: [array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan]), array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan])]
Joint Inicializada: [array([['00000', '1'],
       ['00001', '0'],
       ['00010', '0'],
       ['00011', '1'],
       ['00100', '0'],
       ['00101', '1'],
       ['00110', '1'],
       ['00111', '1'],
       ['01000', '1'],
       ['01001', '1'],
       ['01010', '1'],
       ['01011', '0'],
       ['01100', '1'],
       ['01101', '0'],
       ['01110', '0'],
       ['01111', '1'],
       ['10000', '0'],
       ['10001', '0'],
       ['10010', '1'],
       ['10011', '0'],
       ['10100', '1'],
       ['10101', '0'],
       ['10110', '1'],
       ['10111', '1'],
       ['11000', '0'],
       ['11001', '0'],
       ['11010', '0'],
       ['11011', '1'],
       ['11100', '0'],
       ['11101', '0'],
       ['11110', '0'],
       ['11111', '0']], dtype='<U11'), array([['00000', '0'],
       ['00001', '1'],
       ['00010', '0'],
       ['00011', '0'],
     

In [3]:
USDMM.initialize_parameters_nn([np.array([np.nan,  1., np.nan,  1.,  1.,  1., np.nan,  1., np.nan]),np.array([np.nan,  1., np.nan,  1.,  1.,  1., np.nan,  1., np.nan])])

AttributeError: module 'USDMM_v3' has no attribute 'initialize_parameters_nn'

In [36]:
def mat(a,b):
    c = a+b
    

In [37]:
mat(1,2)

In [41]:
2**2

4

In [49]:
for i in range(100000000):
    mat(i,i**2)

In [51]:
from multiprocessing import Pool

In [52]:
with Pool(8) as p:
    p.map(mat,i,i**2)

TypeError: 'int' object is not iterable

In [50]:
with concurrent.futures.ThreadPoolExecutor() as executor:
    [executor.submit(mat,i,i**2) for i in range(100000000)]

KeyboardInterrupt: 

In [53]:
def f(x):
    return x*x

In [55]:
with Pool(5) as p:
    print(p.map(f, [1, 2, 3]))

Process SpawnPoolWorker-20:
Process SpawnPoolWorker-19:
Process SpawnPoolWorker-21:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/mariana.feldman/opt/anaconda3/envs/envpy/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/mariana.feldman/opt/anaconda3/envs/envpy/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mariana.feldman/opt/anaconda3/envs/envpy/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/mariana.feldman/opt/anaconda3/envs/envpy/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/mariana.feldman/opt/anaconda3/envs/envpy/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
  File "/Users/mariana.feldman/opt/anaconda3/env

KeyboardInterrupt: 

In [1]:
def fib(n):
    return n if n < 2 else fib(n - 2) + fib(n - 1)

In [2]:
import os
import threading

In [3]:
os.cpu_count()

8

In [4]:
for _ in range(os.cpu_count()):
    threading.Thread(target=fib, args=(35,)).start()

In [7]:
fib(40)

102334155

In [8]:
for _ in range(os.cpu_count()):
    threading.Thread(target=fib, args=(40,)).start()

In [10]:
import multiprocessing


In [12]:
for b in [1,10]:
    print(b)

1
10


In [11]:
if __name__ == "__main__":
    for _ in range(multiprocessing.cpu_count()):
        multiprocessing.Process(target=fib, args=(40,)).start()

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mariana.feldman/opt/anaconda3/envs/envpy/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/mariana.feldman/opt/anaconda3/envs/envpy/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'fib' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mariana.feldman/opt/anaconda3/envs/envpy/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/mariana.feldman/opt/anaconda3/envs/envpy/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'fib' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "<string