In [1]:
import numpy as np
import itertools
import cv2
import random
import copy
from time import sleep, time
import pickle
import concurrent.futures
import os
import pandas as pd

In [2]:
import USDMM_v2 as USDMM_2

WOMC = USDMM_2.WOMC(
    new = True, # True/ STR -> If True inicialize with the cross operator/ If STR it will opens the file with the name passed
    nlayer = 2, # INT -> Number of operators in each layer
    wlen = 3,  # INT -> Size of the operator (wlen*wlen)
    train_size = 10, # INT -> Number of images to train 
    val_size = 10, # INT -> Number of images to validate
    test_size = 10, # INT -> Number of images to test
    error_type = 'iou', # 'mae' / 'iou' -> type of error
    neighbors_sample = False, # INT/False -> Number of neighbors to sort
    epoch_f = 10, # INT -> Number of epochs for the boolean function lattice (fixed windows)
    epoch_w = 50, # INT -> Number of epochs for the windows lattice
    batch = 10, # INT -> Batch size
    path_results = 'results_V2', # STR -> file where we want to save the results
    name_save='_V2', # STR -> pos fixed name for the results saved
    seed = 0, #INT -> seed for reproducibilit
    parallel = True, # True/False -> use parallel (True) or sequential (False)
    early_stop_round_f = 20, #INT -> max number of epochs without changes in the boolean function lattice
    early_stop_round_w = 10 #INT -> max number of epochs without changes in the windows lattice
)


#WOMC.results_after_fit()

Janela Inicializada: [array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan]), array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan])]
Joint Inicializada: [array([['00000', '1'],
       ['00001', '0'],
       ['00010', '0'],
       ['00011', '1'],
       ['00100', '0'],
       ['00101', '1'],
       ['00110', '1'],
       ['00111', '1'],
       ['01000', '1'],
       ['01001', '1'],
       ['01010', '1'],
       ['01011', '0'],
       ['01100', '1'],
       ['01101', '0'],
       ['01110', '0'],
       ['01111', '1'],
       ['10000', '0'],
       ['10001', '0'],
       ['10010', '1'],
       ['10011', '0'],
       ['10100', '1'],
       ['10101', '0'],
       ['10110', '1'],
       ['10111', '1'],
       ['11000', '0'],
       ['11001', '0'],
       ['11010', '0'],
       ['11011', '1'],
       ['11100', '0'],
       ['11101', '0'],
       ['11110', '0'],
       ['11111', '0']], dtype='<U11'), array([['00000', '0'],
       ['00001', '1'],
       ['00010', '0'],
       ['00011', '0'],
     

In [2]:
Wtrain2,w_error2, W2, joint2 = WOMC.test2()

In [3]:
joint3, error3,f_epoch_min = WOMC.get_error_window_parallel(W2,joint2,0)
error3, f_epoch_min

inicial error: 0.9819856336725579
Epoch: 1: / error: 0.8794087900722621 / ix_run: 00
Min error!!
Epoch: 2: / error: 0.8202385515516838 / ix_run: 08
Min error!!
Epoch: 3: / error: 0.7492607248438035 / ix_run: 028
Min error!!
Epoch: 4: / error: 0.7325039955478129 / ix_run: 022
Min error!!
Epoch: 5: / error: 0.7143034455366941 / ix_run: 023
Min error!!
Epoch: 6: / error: 0.658144606811632 / ix_run: 07
Min error!!
Epoch: 7: / error: 0.6432813063414392 / ix_run: 015
Min error!!
Epoch: 8: / error: 0.6252427460365892 / ix_run: 027
Min error!!
Epoch: 9: / error: 0.6190743481502106 / ix_run: 06
Min error!!
Epoch: 10: / error: 0.6174760123377236 / ix_run: 012
Min error!!


(array([0.61747601, 0.61736838]), 10)

In [5]:
import USDMM as USDMM

WOMC = USDMM.WOMC(
    new = True, # True/ STR -> If True inicialize with the cross operator/ If STR it will opens the file with the name passed
    nlayer = 2, # INT -> Number of operators in each layer
    wlen = 3,  # INT -> Size of the operator (wlen*wlen)
    train_size = 10, # INT -> Number of images to train 
    val_size = 10, # INT -> Number of images to validate
    test_size = 10, # INT -> Number of images to test
    error_type = 'iou', # 'mae' / 'iou' -> type of error
    neighbors_sample = False, # INT/False -> Number of neighbors to sort
    epoch_f = 10, # INT -> Number of epochs for the boolean function lattice (fixed windows)
    epoch_w = 50, # INT -> Number of epochs for the windows lattice
    batch = 10, # INT -> Batch size
    path_results = 'results_V4', # STR -> file where we want to save the results
    name_save='_V4', # STR -> pos fixed name for the results saved
    seed = 0, #INT -> seed for reproducibilit
    parallel = True, # True/False -> use parallel (True) or sequential (False)
    early_stop_round_f = 20, #INT -> max number of epochs without changes in the boolean function lattice
    early_stop_round_w = 10 #INT -> max number of epochs without changes in the windows lattice
)

Janela Inicializada: [array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan]), array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan])]
Joint Inicializada: [array([['00000', '1'],
       ['00001', '0'],
       ['00010', '0'],
       ['00011', '1'],
       ['00100', '0'],
       ['00101', '1'],
       ['00110', '1'],
       ['00111', '1'],
       ['01000', '1'],
       ['01001', '1'],
       ['01010', '1'],
       ['01011', '0'],
       ['01100', '1'],
       ['01101', '0'],
       ['01110', '0'],
       ['01111', '1'],
       ['10000', '0'],
       ['10001', '0'],
       ['10010', '1'],
       ['10011', '0'],
       ['10100', '1'],
       ['10101', '0'],
       ['10110', '1'],
       ['10111', '1'],
       ['11000', '0'],
       ['11001', '0'],
       ['11010', '0'],
       ['11011', '1'],
       ['11100', '0'],
       ['11101', '0'],
       ['11110', '0'],
       ['11111', '0']], dtype='<U11'), array([['00000', '0'],
       ['00001', '1'],
       ['00010', '0'],
       ['00011', '0'],
     

In [6]:
Wtrain,w_error, W, joint = WOMC.test2()

In [7]:
joint4, error4,f_epoch_min = WOMC.get_error_window_parallel(W,joint,0)
error4, f_epoch_min

inicial error: 0.9819856336725579
Epoch: 1: / error: 0.8794087900722621 / ix_run: 00


KeyboardInterrupt: 

In [8]:
import numpy as np
error_hist = np.load('./results_V4/run/error_ep_1.txt', allow_pickle=True)
error_hist2 = np.load('./results_V2/run/error_ep_1.txt', allow_pickle=True)

In [11]:
min(error_hist['error']), min(error_hist2['error'])

(0.8794087900722621, 0.9819856336725579)

In [14]:
len(error_hist['error']), len(error_hist2['error'])

(64, 64)

In [20]:
error_hist['joint'][0][0][0][1]

'1'

In [21]:
for i in range(len(error_hist['joint'])):
    #if error_hist['error'][i] !=error_hist2['error'][i]:
        #print(i)
    count = 0
    for k in range(2):
        for j in range(len(error_hist['joint'][i][k])):
            if error_hist['joint'][i][k][j][1] != error_hist['joint'][i][k][j][1]:
                count+=1
    print(f'round - {i} / count ={count}')

round - 0 / count =0
round - 1 / count =0
round - 2 / count =0
round - 3 / count =0
round - 4 / count =0
round - 5 / count =0
round - 6 / count =0
round - 7 / count =0
round - 8 / count =0
round - 9 / count =0
round - 10 / count =0
round - 11 / count =0
round - 12 / count =0
round - 13 / count =0
round - 14 / count =0
round - 15 / count =0
round - 16 / count =0
round - 17 / count =0
round - 18 / count =0
round - 19 / count =0
round - 20 / count =0
round - 21 / count =0
round - 22 / count =0
round - 23 / count =0
round - 24 / count =0
round - 25 / count =0
round - 26 / count =0
round - 27 / count =0
round - 28 / count =0
round - 29 / count =0
round - 30 / count =0
round - 31 / count =0
round - 32 / count =0
round - 33 / count =0
round - 34 / count =0
round - 35 / count =0
round - 36 / count =0
round - 37 / count =0
round - 38 / count =0
round - 39 / count =0
round - 40 / count =0
round - 41 / count =0
round - 42 / count =0
round - 43 / count =0
round - 44 / count =0
round - 45 / count =

In [7]:
joint4, error4,f_epoch_min = WOMC.get_error_window_parallel(W,joint,0)
error4, f_epoch_min

(array([0.61383145, 0.60987238]), 14)

In [9]:
import pickle
pickle.dump(joint4, open('joint4', 'wb'))

In [3]:
import pickle
pickle.dump(W2, open('W', 'wb'))

In [6]:
path_results = 'results_V4'
name_save = '_V4'

In [7]:
import numpy as np

In [8]:
joint = np.load(f'{path_results}/joint{name_save}.txt', allow_pickle=True)
W = np.load(f'{path_results}/W{name_save}.txt', allow_pickle=True)

In [10]:
W

[array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan]),
 array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan])]

In [5]:
WOMC.results_after_fit('results_V4', '_V4')

Reading from: results_V4
Train error: 0.6138314515405996 / Validation error: 0.609872383871108 / Test error: 0.6210821757434946


TypeError: 'int' object is not subscriptable

In [8]:
joint4

[array([['00000', '0'],
        ['00001', '0'],
        ['00010', '0'],
        ['00011', '1'],
        ['00100', '0'],
        ['00101', '0'],
        ['00110', '0'],
        ['00111', '0'],
        ['01000', '0'],
        ['01001', '1'],
        ['01010', '0'],
        ['01011', '1'],
        ['01100', '0'],
        ['01101', '0'],
        ['01110', '1'],
        ['01111', '0'],
        ['10000', '0'],
        ['10001', '0'],
        ['10010', '1'],
        ['10011', '0'],
        ['10100', '1'],
        ['10101', '0'],
        ['10110', '0'],
        ['10111', '0'],
        ['11000', '0'],
        ['11001', '0'],
        ['11010', '0'],
        ['11011', '0'],
        ['11100', '1'],
        ['11101', '0'],
        ['11110', '0'],
        ['11111', '0']], dtype='<U11'),
 array([['00000', '0'],
        ['00001', '1'],
        ['00010', '0'],
        ['00011', '0'],
        ['00100', '1'],
        ['00101', '0'],
        ['00110', '1'],
        ['00111', '1'],
        ['01000', '1'],


In [ ]:
error3==error4

In [11]:
w_error == w_error2

(0.9819856336725579, 0.9819856336725579)

In [42]:
w_error, w_error2

(0.9819856336725579, 0.9825991306050732)

In [12]:
count = 0
for k in range(2):
    for j in range(len(joint[k])):
        if joint[k][j][1] != joint2[k][j][1]:
            count+=1
count

0

In [13]:
W, W2

([array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan]),
  array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan])],
 [array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan]),
  array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan])])

In [14]:
len(Wtrain)

10

In [15]:
len(Wtrain[0])

2

In [16]:
Wtrain[0][1] == Wtrain2[0][1]

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [17]:
import numpy as np

In [18]:
for k in range(len(Wtrain)):
    print(np.all(Wtrain[k][-1] == Wtrain2[k][-1]))

True
True
True
True
True
True
True
True
True
True


In [6]:
train, ytrain = WOMC.get_images(10, 'train')

In [7]:
train

[array([[-1., -1., -1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1., -1.],
        ...,
        [-1., -1., -1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1., -1.]]),
 array([[-1., -1., -1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1., -1.],
        ...,
        [-1., -1., -1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1., -1.]]),
 array([[-1., -1., -1., ..., -1., -1., -1.],
        [-1., -1.,  1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1., -1.],
        ...,
        [-1., -1., -1., ..., -1., -1., -1.],
        [-1.,  1., -1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1., -1.]]),
 array([[-1., -1., -1., ..., -1., -1., -1.],
        [-1., -1., -1., ..., -1., -1.,  1.],
        [-1., -1., -1., ..., -1., -1., -1.],
        ..

In [9]:
train[0].shape

(56, 56)

In [11]:
import numpy as np

In [14]:
np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12],[13,14,15,16]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
tt = np.array([[1,2,3,5,6,7,9,10,11],[2,3,4,6,7,8,10,11,12],[5,6,7,9,10,11,13,14,15],[6,7,8,10,11,12,14,15,16]])

In [19]:
tt

array([[ 1,  2,  3,  5,  6,  7,  9, 10, 11],
       [ 2,  3,  4,  6,  7,  8, 10, 11, 12],
       [ 5,  6,  7,  9, 10, 11, 13, 14, 15],
       [ 6,  7,  8, 10, 11, 12, 14, 15, 16]])

In [20]:
Wini = np.array([np.nan, 1., np.nan, 1., 1., 1., np.nan, 1., np.nan])

In [41]:
arr = tt*Wini
arr

array([[nan,  2., nan,  5.,  6.,  7., nan, 10., nan],
       [nan,  3., nan,  6.,  7.,  8., nan, 11., nan],
       [nan,  6., nan,  9., 10., 11., nan, 14., nan],
       [nan,  7., nan, 10., 11., 12., nan, 15., nan]])

In [42]:
cleaned_array = [row[~np.isnan(row)] for row in arr]
result_array = np.array(cleaned_array)
result_array

array([[ 2.,  5.,  6.,  7., 10.],
       [ 3.,  6.,  7.,  8., 11.],
       [ 6.,  9., 10., 11., 14.],
       [ 7., 10., 11., 12., 15.]])

In [23]:
wlen = 3
increase = int(round(wlen/2-0.1,0))

In [69]:
def get_images(img_size, img_type):
    ximg = []
    yimg = []
    for img in range(1,img_size+1):
        x = cv2.imread(f'./data/x/{img_type}{img:02d}.jpg', cv2.IMREAD_GRAYSCALE)
        y = cv2.imread(f'./data/y/{img_type}{img:02d}.jpg', cv2.IMREAD_GRAYSCALE)
        xbin = _convert_binary(x)
        xbin_inc = increase_zero(xbin)
        ybin = _convert_binary(y)
        for i in range(xbin.shape[0]):
            for j in range(xbin.shape[1]):
                window = np.array(xbin_inc[i:i + wlen, j:j + wlen]).flatten()
                window = (xbin_inc[i:i + wlen, j:j + wlen]).flatten()
                ximg.append(window)
                yimg.append(ybin[i, j])
    return np.vstack(ximg) , np.array(yimg)

def increase_zero(img):
    img_inc = -np.ones((img.shape[0]+increase*2, img.shape[1]+increase*2), dtype=img.dtype)
    img_inc[increase:img_inc.shape[0]-increase,increase:img_inc.shape[1]-increase] = img
    return img_inc

def _convert_binary(img):
    (_, img_bin) = cv2.threshold(img, 100, 255, cv2.THRESH_BINARY)
    img_bin = img_bin.astype('float64')
    img_bin[(img_bin==0)]=1
    img_bin[(img_bin==255)]=-1    
    return img_bin

In [70]:
train_size = 10
img_type = 'train'

In [71]:
x, y = get_images(train_size, 'train')

In [74]:
x.shape, y.shape

((31360, 9), (31360,))

In [78]:
xbin.shape[0]

56

In [87]:
W = []
W.append(np.array([np.nan, 1., np.nan, 1., 1., 1., np.nan, 1., np.nan]))
W.append(np.array([np.nan, 1., np.nan, 1., 1., 1., np.nan, 1., np.nan]))
np.nansum(W, axis=1)

array([5., 5.])

In [84]:
2**5

32

In [65]:
a = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15]])

In [68]:
a.flatten().values

AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [17]:
import numpy as np

def sliding_window(matrix, window_size):
    """
    Generate submatrices using a sliding window over a 2D matrix.

    Args:
        matrix (numpy.ndarray): The input 2D matrix.
        window_size (tuple): A tuple (height, width) representing the window size.

    Yields:
        numpy.ndarray: Submatrices corresponding to each position of the sliding window.
    """
    if not isinstance(matrix, np.ndarray):
        matrix = np.array(matrix)

    if not isinstance(window_size, tuple) or len(window_size) != 2:
        raise ValueError("window_size must be a tuple of two integers (height, width).")

    height, width = window_size
    matrix_height, matrix_width = matrix.shape

    if height > matrix_height or width > matrix_width:
        raise ValueError("Window size exceeds the matrix dimensions.")

    for i in range(matrix_height - height + 1):
        for j in range(matrix_width - width + 1):
            window = matrix[i:i + height, j:j + width].fl
            yield window

# Example usage:
matrix = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15]])

window_size = (2, 2)

for submatrix in sliding_window(matrix, window_size):
    print(submatrix)


[[1 2]
 [6 7]]
[[2 3]
 [7 8]]
[[3 4]
 [8 9]]
[[ 4  5]
 [ 9 10]]
[[ 6  7]
 [11 12]]
[[ 7  8]
 [12 13]]
[[ 8  9]
 [13 14]]
[[ 9 10]
 [14 15]]


In [37]:
np.array(submatrix).flatten()

array([ 9, 10, 14, 15])

In [35]:
a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

In [2]:
import USDMM_v3 as USDMM

WOMC = USDMM.WOMC(
    new = True, # True/ STR -> If True inicialize with the cross operator/ If STR it will opens the file with the name passed
    nlayer = 2, # INT -> Number of operators in each layer
    wlen = 3,  # INT -> Size of the operator (wlen*wlen)
    train_size = 10, # INT -> Number of images to train 
    val_size = 10, # INT -> Number of images to validate
    test_size = 10, # INT -> Number of images to test
    error_type = 'iou', # 'mae' / 'iou' -> type of error
    neighbors_sample = False, # INT/False -> Number of neighbors to sort
    epoch_f = 10, # INT -> Number of epochs for the boolean function lattice (fixed windows)
    epoch_w = 50, # INT -> Number of epochs for the windows lattice
    batch = 10, # INT -> Batch size
    path_results = 'results_V4', # STR -> file where we want to save the results
    name_save='_V4', # STR -> pos fixed name for the results saved
    seed = 0, #INT -> seed for reproducibilit
    parallel = True, # True/False -> use parallel (True) or sequential (False)
    early_stop_round_f = 20, #INT -> max number of epochs without changes in the boolean function lattice
    early_stop_round_w = 10 #INT -> max number of epochs without changes in the windows lattice
)

Janela Inicializada: [array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan]), array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan])]
Joint Inicializada: [array([['00000', '1'],
       ['00001', '0'],
       ['00010', '0'],
       ['00011', '1'],
       ['00100', '0'],
       ['00101', '1'],
       ['00110', '1'],
       ['00111', '1'],
       ['01000', '1'],
       ['01001', '1'],
       ['01010', '1'],
       ['01011', '0'],
       ['01100', '1'],
       ['01101', '0'],
       ['01110', '0'],
       ['01111', '1'],
       ['10000', '0'],
       ['10001', '0'],
       ['10010', '1'],
       ['10011', '0'],
       ['10100', '1'],
       ['10101', '0'],
       ['10110', '1'],
       ['10111', '1'],
       ['11000', '0'],
       ['11001', '0'],
       ['11010', '0'],
       ['11011', '1'],
       ['11100', '0'],
       ['11101', '0'],
       ['11110', '0'],
       ['11111', '0']], dtype='<U11'), array([['00000', '0'],
       ['00001', '1'],
       ['00010', '0'],
       ['00011', '0'],
     

In [3]:
USDMM.initialize_parameters_nn([np.array([np.nan,  1., np.nan,  1.,  1.,  1., np.nan,  1., np.nan]),np.array([np.nan,  1., np.nan,  1.,  1.,  1., np.nan,  1., np.nan])])

AttributeError: module 'USDMM_v3' has no attribute 'initialize_parameters_nn'