In [1]:
import numpy as np
import itertools
import cv2
import random
import copy
from time import sleep, time
import pickle
import concurrent.futures
import os
import pandas as pd

In [2]:
import USDMM
import USDMM_v2
import USDMM_v3

In [3]:
WOMC = USDMM.WOMC(
    new = True, # True/ STR -> If True inicialize with the cross operator/ If STR it will opens the file with the name passed
    nlayer = 2, # INT -> Number of operators in each layer
    wlen = 3,  # INT -> Size of the operator (wlen*wlen)
    train_size = 10, # INT -> Number of images to train 
    val_size = 10, # INT -> Number of images to validate
    test_size = 10, # INT -> Number of images to test
    error_type = 'iou', # 'mae' / 'iou' -> type of error
    neighbors_sample = False, # INT/False -> Number of neighbors to sort
    epoch_f = 10, # INT -> Number of epochs for the boolean function lattice (fixed windows)
    epoch_w = 50, # INT -> Number of epochs for the windows lattice
    batch = 10, # INT -> Batch size
    path_results = 'results_V2', # STR -> file where we want to save the results
    name_save='_V2', # STR -> pos fixed name for the results saved
    seed = 0, #INT -> seed for reproducibilit
    parallel = True, # True/False -> use parallel (True) or sequential (False)
    early_stop_round_f = 20, #INT -> max number of epochs without changes in the boolean function lattice
    early_stop_round_w = 10 #INT -> max number of epochs without changes in the windows lattice
)

Janela Inicializada: [array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan]), array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan])]
Joint Inicializada: [array([['00000', '1'],
       ['00001', '0'],
       ['00010', '0'],
       ['00011', '1'],
       ['00100', '0'],
       ['00101', '1'],
       ['00110', '1'],
       ['00111', '1'],
       ['01000', '1'],
       ['01001', '1'],
       ['01010', '1'],
       ['01011', '0'],
       ['01100', '1'],
       ['01101', '0'],
       ['01110', '0'],
       ['01111', '1'],
       ['10000', '0'],
       ['10001', '0'],
       ['10010', '1'],
       ['10011', '0'],
       ['10100', '1'],
       ['10101', '0'],
       ['10110', '1'],
       ['10111', '1'],
       ['11000', '0'],
       ['11001', '0'],
       ['11010', '0'],
       ['11011', '1'],
       ['11100', '0'],
       ['11101', '0'],
       ['11110', '0'],
       ['11111', '0']], dtype='<U21'), array([['00000', '0'],
       ['00001', '1'],
       ['00010', '0'],
       ['00011', '0'],
     

In [4]:
WOMC2 = USDMM_v2.WOMC(
    new = True, # True/ STR -> If True inicialize with the cross operator/ If STR it will opens the file with the name passed
    nlayer = 2, # INT -> Number of operators in each layer
    wlen = 3,  # INT -> Size of the operator (wlen*wlen)
    train_size = 10, # INT -> Number of images to train 
    val_size = 10, # INT -> Number of images to validate
    test_size = 10, # INT -> Number of images to test
    error_type = 'iou', # 'mae' / 'iou' -> type of error
    neighbors_sample = False, # INT/False -> Number of neighbors to sort
    epoch_f = 10, # INT -> Number of epochs for the boolean function lattice (fixed windows)
    epoch_w = 50, # INT -> Number of epochs for the windows lattice
    batch = 10, # INT -> Batch size
    path_results = 'results_V2', # STR -> file where we want to save the results
    name_save='_V2', # STR -> pos fixed name for the results saved
    seed = 0, #INT -> seed for reproducibilit
    parallel = True, # True/False -> use parallel (True) or sequential (False)
    early_stop_round_f = 20, #INT -> max number of epochs without changes in the boolean function lattice
    early_stop_round_w = 10 #INT -> max number of epochs without changes in the windows lattice
)

Janela Inicializada: [array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan]), array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan])]
Joint Inicializada: [array([['00000', '1'],
       ['00001', '0'],
       ['00010', '0'],
       ['00011', '1'],
       ['00100', '0'],
       ['00101', '1'],
       ['00110', '1'],
       ['00111', '1'],
       ['01000', '1'],
       ['01001', '1'],
       ['01010', '1'],
       ['01011', '0'],
       ['01100', '1'],
       ['01101', '0'],
       ['01110', '0'],
       ['01111', '1'],
       ['10000', '0'],
       ['10001', '0'],
       ['10010', '1'],
       ['10011', '0'],
       ['10100', '1'],
       ['10101', '0'],
       ['10110', '1'],
       ['10111', '1'],
       ['11000', '0'],
       ['11001', '0'],
       ['11010', '0'],
       ['11011', '1'],
       ['11100', '0'],
       ['11101', '0'],
       ['11110', '0'],
       ['11111', '0']], dtype='<U21'), array([['00000', '0'],
       ['00001', '1'],
       ['00010', '0'],
       ['00011', '0'],
     

In [5]:
WOMC3 = USDMM_v3.WOMC(
    new = True, # True/ STR -> If True inicialize with the cross operator/ If STR it will opens the file with the name passed
    nlayer = 2, # INT -> Number of operators in each layer
    wlen = 3,  # INT -> Size of the operator (wlen*wlen)
    train_size = 10, # INT -> Number of images to train 
    val_size = 10, # INT -> Number of images to validate
    test_size = 10, # INT -> Number of images to test
    error_type = 'iou', # 'mae' / 'iou' -> type of error
    neighbors_sample = False, # INT/False -> Number of neighbors to sort
    epoch_f = 10, # INT -> Number of epochs for the boolean function lattice (fixed windows)
    epoch_w = 50, # INT -> Number of epochs for the windows lattice
    batch = 10, # INT -> Batch size
    path_results = 'results_V2', # STR -> file where we want to save the results
    name_save='_V2', # STR -> pos fixed name for the results saved
    seed = 0, #INT -> seed for reproducibilit
    parallel = True, # True/False -> use parallel (True) or sequential (False)
    early_stop_round_f = 20, #INT -> max number of epochs without changes in the boolean function lattice
    early_stop_round_w = 10 #INT -> max number of epochs without changes in the windows lattice
)

Janela Inicializada: [array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan]), array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan])]
Resultados serão salvos em  results_V2
------------------------------------------------------------------


In [6]:
(joint, error, epoch_min) = WOMC.get_error_window(WOMC.W, WOMC.joint, 0)

In [7]:
error

array([0.61747601, 0.61736838])

In [37]:
(joint, error, epoch_min) = WOMC.get_error_window_parallel(WOMC.W, WOMC.joint, 0)
error

array([0.61747601, 0.61736838])

In [8]:
epoch_min

9

In [9]:
(joint, error, epoch_min) = WOMC2.get_error_window(WOMC.W, WOMC.joint, 0)

In [38]:
(joint, error, epoch_min) = WOMC2.get_error_window_parallel(WOMC.W, WOMC.joint, 0)
error

array([0.61747601, 0.61736838])

In [28]:
WOMC2.W

[array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan]),
 array([nan,  1., nan,  1.,  1.,  1., nan,  1., nan])]

In [29]:
W = np.array([np.nan, np.nan,np.nan,np.nan, 1., 1., np.nan, np.nan, np.nan])

In [33]:
W = [W,W]

In [31]:
joint = WOMC2.create_joint(W)

In [34]:
joint = [joint, joint]

In [36]:
joint

[array([['00', '1'],
        ['01', '0'],
        ['10', '0'],
        ['11', '1']], dtype='<U21'),
 array([['00', '1'],
        ['01', '0'],
        ['10', '0'],
        ['11', '1']], dtype='<U21')]

In [35]:
WOMC2.create_w_matrices(W,joint)

[[array([[ 0.,  0.,  0.],
         [ 0., -1., -1.],
         [ 0.,  0.,  0.]]),
  array([[0., 0., 0.],
         [0., 1., 1.],
         [0., 0., 0.]])],
 [array([[ 0.,  0.,  0.],
         [ 0., -1., -1.],
         [ 0.,  0.,  0.]]),
  array([[0., 0., 0.],
         [0., 1., 1.],
         [0., 0., 0.]])]]

In [10]:
error

array([0.61747601, 0.61736838])

In [11]:
epoch_min

9

In [24]:
X, y, x_shape = WOMC3.get_images_2(WOMC3.train_size, 'train')

In [25]:
nn_parameters = WOMC3.initialize_parameters_nn(WOMC3.W)

In [16]:
parameters, costs = WOMC3.nn_model_train(X, y, nn_parameters, learning_rate=0.01, num_iterations = 2000, print_cost = False )

Cost after iteration 1999: 0.9067064786671265


In [20]:
parameters, costs = WOMC3.nn_model_train(X, y, nn_parameters, learning_rate=0.1, num_iterations = 2000, print_cost = False )

Cost after iteration 1999: 0.9023278720586921


In [23]:
parameters, costs = WOMC3.nn_model_train(X, y, nn_parameters, learning_rate=0.5, num_iterations = 2000, print_cost = False )

Cost after iteration 1999: 0.9022375244514118


In [26]:
parameters, costs = WOMC3.nn_model_train(X, y, nn_parameters, learning_rate=1, num_iterations = 2000, print_cost = False )

Cost after iteration 1999: 0.9141664791644212
